name: Build All and Deploy

on:
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build App
      uses: ./.github/workflows/build-app.yaml

  build_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Server
      uses: ./.github/workflows/build-server.yaml