name: Build All and Deploy

on:
  workflow_dispatch:

jobs:
  build_app:
    uses: ./.github/workflows/build-component.yaml
    with:
      component: app

  build_server:
    uses: ./.github/workflows/build-component.yaml
    with:
      component: server