name: Build All and Deploy

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build_app:
    uses: ./.github/workflows/build-component.yaml
    with:
      component: app

  build_server:
    uses: ./.github/workflows/build-component.yaml
    with:
      component: server

  deploy_all:
    needs: [build_app, build_server]
    uses: ./.github/workflows/deploy.yaml